### ISSUE TITLE
everyone needs access to the jban command

### ISSUE THREAD

**Issue by samiscool51** [Sonnet-Discord/sonnet-py#28]
dude like everyone wants to jban eachother why dont you allow us to jban eachother

**Comment by Saragon4005** [comment]
The jban command was made to be derived from the ban command. The command thus emulates every part of the ban command and was only intended for people who already had access to the ban command to do so they could safely joke around as telling them not to use the ban command was not an option. Allowing anyone to use the jban command could also cause confusion as it looks exactly like an actual ban by design and could cause confusion weather the user actually has that kind of power
