### ISSUE TITLE
Account Filtering (based on filters)

### ISSUE THREAD

**Issue by xFuney** [Sonnet-Discord/sonnet-py#57]
Allows server administrators to monitor different aspects of newly joined users such as:

- Regular expression blacklist on usernames 
- Join date filter (e.g. throw newly created accounts into interstitial mute state)
- Profile picture checks (if they are a new account and have no profile picture)

Different actions can be assigned to this being triggered, similar to the systems used for the regex notifier. Would be a great enhancement for large servers - it would assist with weeding out bad actors, while still allowing potentially OK users to still pass through the interstitial after being queried by the moderators/administrators.

**Comment by ultrabear** [comment]
_thanks discord.py_, default avatar checking is jank but it _exists_
ill implement it as notifier logs, throwing someone in a mute state purely because they are a new account is simply over reliance on bots, and sounds like it would cause a nightmare as tuning such a system to keep good people is simply not something a few lines of code can do
notifiers can be implemented for all 3, with tuning options
username blacklist can be rolled into the regular blacklist processor, probably

**Comment by ultrabear** [comment]
so ive looked at it more and decided
ill add flags to notifier log
no automute or autoban or whatever

**Comment by ultrabear** [comment]
Completed: a00af676c12c6dbdc70ba9065335e2427d3c911c
